### ISSUE TITLE
Consider adding game states

### ISSUE THREAD

**Issue by John2T** [COMP2522/project-cactus-club#160] opened 2023-03-27 22:14 UTC
Mainly quality of life changes but adding a start screen before automatically starting the game, with controls of games displayed. Additionally Adding a game restart or game over once all bricks(?) have been destroyed so the game does not loop forever.

**Comment by JVViacrusis** [comment] 2023-04-03 03:12
Duplicate of #181, #180 and others

**Closed as completed by JVViacrusis** 2023-04-03 03:12 UTC
Labels: duplicate
